# Generated by Django 4.1.7 on 2023-03-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreviews',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='userreviews',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
