# Generated by Django 4.1.7 on 2023-03-17 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_rename_created_at_userreviews_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReviews',
            new_name='UserReview',
        ),
    ]
