# Generated by Django 4.1.7 on 2023-03-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamescore_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
